### ISSUE TITLE
Rotation?

### ISSUE THREAD

**Issue by ghost** [TheCherno/Cherno#19]
Will the engine have rotation? Should it?

**Comment by SebastienGllmt** [comment]
If you look at our Texture.java class (https://github.com/TheCherno/Cherno/blob/master/Cherno/src/com/thecherno/cherno/engine/graphics/Texture.java) we're creating a BufferedImage and then throwing it away in favor of a pixel array. If we want things like rotation, I suggest we stop using pixel arrays you can use the createGraphics method in the BufferedImage class to gain access to all the methods here http://docs.oracle.com/javase/7/docs/api/java/awt/Graphics2D.html which includes rotate and many other tools.

**Comment by TheCherno** [comment]
Rotation will be done, using pixel arrays.
